version: "3.3"

networks:
  devnet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

services:
  ganache:
    image: "trufflesuite/ganache-cli:latest"
    container_name: ganache
    networks:
      - devnet-network
    volumes:
      - ./data:/root/data
    ports:
      - "9545:9545"


  rabbit0:
    image: "rabbitmq:3-management"
    container_name: rabbit0
    networks:
      - devnet-network

  heimdall0:
    image: "maticnetwork/heimdall:v0.2.1-mumbai"
    container_name: heimdall0
    depends_on:
      - rabbit0
    networks:
      - devnet-network
    volumes:
      - ./devnet/node0/heimdalld:/root/.heimdalld
      - ./devnet/node0/heimdallcli:/root/.heimdallcli
      - ./logs/node0/heimdall:/root/heimdall/logs
    
    ports:
      - "1317:1317"
      - "26657:26657"
    
  
  bor0:
    image: "maticnetwork/bor:v0.2.5"
    container_name: bor0
    # depends_on:
    #  - heimdall0
    networks:
      devnet-network:
          ipv4_address: 172.20.1.100
    environment:
      - HEIMDALL_URL=http://heimdall0:1317
    volumes:
      - ./devnet/node0/bor:/root/.bor
      - ./logs/node0/bor:/root/logs
    
    ports:
      - "8545:8545"
      - "8546:8546"
    
