apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  ports:
    - port: 5001
      $patch: delete
    - name: http
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  ports:
    - port: 5000
      $patch: delete
    - name: http
      port: 80
      targetPort: 80