[default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
    'ds-test/=node_modules/ds-test/',
    'solmate/=node_modules/solmate/',
]
libraries = []
cache = true
force = false
evm_version = 'london'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
verbosity = 3
ignored_error_codes = []
fuzz_runs = 256
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 0
chain_id = 1
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 0
block_difficulty = 0

