[profile.default]
out = "out"
libs = ['lib', 'node_modules']
block_timestamp = 1
verbosity = 3
solc_version = "0.8.16"
optimizer_runs = 1
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.default.fuzz]
seed="0x64"

[profile.default.fmt]
number_underscore = "thousands"

[profile.default.rpc_endpoints]
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_POLYGON_MUMBAI_KEY}"
goerli = "https://eth-goerli.alchemyapi.io/v2/${ALCHEMY_ETH_GOERLI_KEY}"
ethereum = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_ETH_MAINNET_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_POLYGON_MAINNET_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ARB_MAINNET_KEY}"

[profile.default.etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = 137, url = "https://api.polygonscan.com/" }

[profile.ci.fuzz]
runs = 10000