/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { BaseRelayRecipient__factory } from "./BaseRelayRecipient__factory";
