/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConvexBooster } from "./IConvexBooster";
export type { IConvexRewards } from "./IConvexRewards";
