/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAToken } from "./IAToken";
export type { IAaveIncentivesController } from "./IAaveIncentivesController";
export type { IInitializableAToken } from "./IInitializableAToken";
export type { ILendingPool } from "./ILendingPool";
export type { ILendingPoolAddressesProvider } from "./ILendingPoolAddressesProvider";
export type { ILendingPoolAddressesProviderRegistry } from "./ILendingPoolAddressesProviderRegistry";
export type { IProtocolDataProvider } from "./IProtocolDataProvider";
export type { IScaledBalanceToken } from "./IScaledBalanceToken";
