apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
images:
- name: backend-api
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/backend-api
  newTag: bcd27ff74a1cf52c8faee7219524d24788dec127
- name: data-pipeline
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/data-pipeline
  newTag: 06fd90e68d00888f19744dd427e306f61237cae8
- name: web-frontend
  newName: 959984261658.dkr.ecr.us-east-2.amazonaws.com/web-frontend
  newTag: 9bd0f639b757501b58a04ab8b13d481f1a3fc1bc
resources:
- ../../base
patchesStrategicMerge:
- patch.yml
