apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
spec:
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image:  backend-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  type: LoadBalancer # TODO(nodimdim): Change this to ClusterIP after frontend and backend are connected.
  selector:
    app: backend-api
  ports:
  - name: http
    port: 5001
    targetPort: 8000
