apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-pipeline
spec:
  # https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-pipeline
            image:  data-pipeline
            resources:
              limits:
                memory: "512Mi"
                cpu: "100m"
