apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend-deployment
spec:
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web-frontend
        image:  web-frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: web-frontend
  ports:
  - port: 5000
    targetPort: 80
