org: affinedefi
app: aws-smart-contract-chore
service: rebalancer

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript

functions:
  rebalance:
    handler: handler.run
    events:
      # Invoke Lambda function every 12 hour
      - schedule: rate(12 hours)
