org: affinedefi
app: aws-smart-contract-chore
service: rebalancer
frameworkVersion: "3"
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x

functions:
  rebalance:
    handler: handler.run
    environment:
      ALCHEMY_ETH_URL: ${param:ALCHEMY_ETH_URL}
      ALCHEMY_POLYGON_URL: ${param:ALCHEMY_POLYGON_URL}
      CONTRACT_VERSION: ${param:CONTRACT_VERSION}
      ETH_DEFENDER_RELAYER_API_KEY: ${param:ETH_DEFENDER_RELAYER_API_KEY}
      ETH_DEFENDER_RELAYER_API_SECRET: ${param:ETH_DEFENDER_RELAYER_API_SECRET}
      POLYGON_DEFENDER_RELAYER_API_KEY: ${param:POLYGON_DEFENDER_RELAYER_API_KEY}
      POLYGON_DEFENDER_RELAYER_API_SECRET: ${param:POLYGON_DEFENDER_RELAYER_API_SECRET}
    events:
      # Invoke Lambda function every 12 hour
      - schedule: rate(12 hours)
