/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICToken__factory } from "./ICToken__factory";
export { IComptroller__factory } from "./IComptroller__factory";
