# This workflow builds docker image of data-pipeline, Used for sanity checking PRs.

name: Data Pipeline CI PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - "data-pipeline/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker image
      env:
        ECR_REPOSITORY: data-pipeline
        DOCKERFILE_PATH: data-pipeline
      run: |
        docker build -t $ECR_REPOSITORY:temp ./$DOCKERFILE_PATH/
        echo "Looks good!"