# This workflow builds docker image to run rebalance script.

name: Smart Contracts PR Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on PR
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sanity-check:
    name: PR Sanity Check
    runs-on: ubuntu-latest
    env:
      MNEMONIC: ${{ secrets.MNEMONIC }}
      ALCHEMY_ETH_GOERLI_KEY: ${{ secrets.ALCHEMY_ETH_GOERLI_KEY }}
      ALCHEMY_POLYGON_MUMBAI_KEY: ${{ secrets.ALCHEMY_POLYGON_MUMBAI_KEY }}
      ALCHEMY_ETH_MAINNET_KEY: ${{ secrets.ALCHEMY_ETH_MAINNET_KEY }}
      ALCHEMY_POLYGON_MAINNET_KEY: ${{ secrets.ALCHEMY_POLYGON_MAINNET_KEY }}
      DEFENDER_API_KEY: ${{ secrets.DEFENDER_API_KEY }}
      DEFENDER_API_SECRET: ${{ secrets.DEFENDER_API_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install yarn dependencies
        run: yarn --frozen-lockfile

      # Running snapshot check is not sufficient as it does not run fuzz tests.
      - name: Run forge tests
        run: yarn test

      - name: Check gas snapshots.
        run: yarn snap --check

      - name: Run hardhat tests.
        run: yarn test-hh

      # TODO: add back once slither works again (https://github.com/crytic/slither/issues/1211)
      # - name: Check slither errors
      #   uses: crytic/slither-action@v0.1.1
      #   id: slither
      #   continue-on-error: true
      #   with:
      #     sarif: results.sarif

      # TODO: add back once we have code scanning (https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually)
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}

      - name: Check lint errors
        run: yarn lint

      - name: Check formatting errors
        run: yarn format

      - name: Typescript compiles correctly
        run: yarn tsc
