# This workflow builds docker image to run rebalance script.

name: Smart Contracts PR Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on PR
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sanity-check:
    name: PR Sanity Check
    runs-on: ubuntu-latest
    env:
      ETH_GOERLI_URL:  https://eth-goerli.alchemyapi.io/v2${{ secrets.ALCHEMY_ETH_KEY }}
      POLYGON_MUMBAI_URL: https://polygon-mumbai.g.alchemy.com/v2/${{ secrets.ALCHEMY_POLYGON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install yarn dependencies
        run: yarn --frozen-lockfile

      - name: Build and run tests that doesn't require forking testnets with gas snapshot checks.
        run: |
          forge test --no-match-contract ".*Fork"
          forge snapshot --check --no-match-contract ".*Fork"

      - name: Build and run tests that doesn't require forking against ethereum goerli with gas snapshot checks.
        run: |
          forge test --fork-url ${{ ETH_GOERLI_URL }} --match-contract "L1.*Fork" --fork-block-number 6267635
          forge snapshot --check --fork-url ${{ ETH_GOERLI_URL }} --match-contract "L1.*Fork" --fork-block-number 6267635

      - name: Build and run tests that doesn't require forking against polygon mumbai with gas snapshot checks.
        run: |
          forge test --fork-url ${{ POLYGON_MUMBAI_URL }} --match-contract "L2.*Fork" --fork-block-number 24274280
          forge snapshot --check --fork-url ${{ POLYGON_MUMBAI_URL }} --match-contract "L2.*Fork" --fork-block-number 24274280
      
      - name: Check lint errors
        run: yarn lint

      - name: Check formatting errors
        run: yarn format

      - name: Typescript compiles correctly
        run: yarn tsc

      - name: Check if docker image for rebalancer builds
        run: docker build -t alpine-sc:temp .
