# Upload artifacts to S3 bucket when a new release is started.
name: Release Workflow

# Triggers the workflow on push of a release tag
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  workflow:
    name: Deploy contracts then upload generated ABIs and AddressBook to S3 bucket.
    runs-on: ubuntu-latest
    env:
      # S3 sync env variables
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-2"
      VERSION: ${{ github.event.release.tag_name }}
      # Hardhat env variables
      MNEMONIC: ${{ secrets.MNEMONIC }}
      ALCHEMY_ETH_KEY: ${{ secrets.ALCHEMY_ETH_KEY }}
      ALCHEMY_POLYGON_KEY: ${{ secrets.ALCHEMY_POLYGON_KEY }}
      DEFENDER_API_KEY: ${{ secrets.DEFENDER_API_KEY }}
      DEFENDER_API_SECRET: ${{ secrets.DEFENDER_API_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install yarn dependencies, Ignore lifecycle hooks
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Generate the ABIs
        run: yarn hardhat export-abi

      - name: Run deployment scripts
        run: yarn script scripts/deploy-all.ts --no-fork

      - name: Uploading addressbook to S3 bucket in version spacific subdirectory
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '*' --include 'addressbook.json' --include 'abi/*.json'
        env:
          DEST_DIR: ${{ env.VERSION || 'test' }}

      - name: Uploading addressbook to S3 bucket in `latest` subdirectory
        if: ${{ env.VERSION }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '*' --include 'addressbook.json' --include 'abi/*.json'
        env:
          DEST_DIR: latest
