# This workflow updates production kubernetes config with desired version 
# of web-frontend image.

name: Web Frontend CI Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the production branch
  push:
    branches: [ production ]
    paths:
      - "web-frontend/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Docker image with `github.sha` image tag should already be in ECR from staging workflow.
    - name: Update production kubernetes manifests
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: web-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
       cd deployment/overlays/production
       kustomize edit set image $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       cat kustomization.yml
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump production docker image tag of Web Frontend"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}